# Generated by Django 4.1.3 on 2023-01-22 17:03

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=shop.models.upload_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
